#!/bin/sh
# SPDX-License-Identifier: MIT
# Assigns eth0, eth1, etc. to network interfaces by sorting MAC addresses.
# Run early at boot before the networking service starts.
# Works on boards with any number of Ethernet ports.

set -euo pipefail

RULES_FILE="/etc/udev/rules.d/80-net-mac-sort.rules"

sort_interfaces_by_mac() {
    local iface mac
    for iface in /sys/class/net/*; do
        [ -e "$iface" ] || continue
        iface="$(basename "$iface")"
        [ "$iface" != "lo" ] || continue
        mac="$(cat "$iface/address" 2>/dev/null)" || continue
        [ -n "$mac" ] || continue
        printf '%s\t%s\n' "$mac" "$iface"
    done | sort -t $'\t' -k1,1
}

generate_rules() {
    local mac iface eth_idx=0
    local tmp_file
    mkdir -p /var/tmp
    tmp_file="$(mktemp -p /var/tmp "$RULES_FILE.tmp.XXXXXX")"
    chmod 0644 "$tmp_file"

    printf '# SPDX-License-Identifier: MIT\n' >"$tmp_file"
    printf '# Auto-generated by net-mac-sort: sorts all Ethernet interfaces by MAC, assigns eth0, eth1, ...\n' >>"$tmp_file"

    while IFS=$'\t' read -r mac iface; do
        [ -n "$mac" ] && [ -n "$iface" ] || continue
        printf 'SUBSYSTEM=="net", ATTR{address}=="%s", NAME="eth%d"\n' "$mac" "$eth_idx" >>"$tmp_file"
        eth_idx=$((eth_idx + 1))
    done

    mv "$tmp_file" "$RULES_FILE"
    chmod 0644 "$RULES_FILE"
}

apply_rules() {
    udevadm control --reload-rules 2>/dev/null || true
    local mac iface eth_idx=0
    while IFS=$'\t' read -r mac iface; do
        [ -n "$mac" ] && [ -n "$iface" ] || continue
        if [ -e "/sys/class/net/$iface" ]; then
            udevadm trigger --action=add --subsystem-match=net --attr-match=address="$mac" 2>/dev/null || true
        fi
        eth_idx=$((eth_idx + 1))
    done < <(sort_interfaces_by_mac)
}

main() {
    if [ -d /sys/class/net ]; then
        generate_rules
        apply_rules
    fi
}

main "$@"
