# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Ian Spray

FROM alpine:3.23.3

# ensure /etc/apk/cache is a bind mount to a local tree

RUN apk update && \
    apk add --allow-untrusted \
    alpine-base \
    alpine-sdk \
    abuild \
    mkinitfs \
    genimage \
    e2fsprogs \
    dosfstools \
    mtools \
    busybox \
    util-linux \
    sudo \
    git \
    rsync \
    curl \
    wget \
    linux-lts

RUN addgroup builder && \
    adduser -h /home/builder -G builder -D builder && \
    echo 'builder ALL=(ALL) NOPASSWD: /sbin/apk' >> /etc/sudoers && \
    echo 'SUDO_APK="sudo /sbin/apk --no-interactive --no-network --no-cache --allow-untrusted"' >> /etc/abuild.conf

COPY /tools/abuild-pkg.sh /usr/bin/
COPY /tools/alpian-build.sh /usr/bin/

WORKDIR /work

CMD ["/bin/sh"]
